trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  nodeVersion: '20.x'

steps:
  - checkout: self
    clean: true

  - task: NodeTool@0
    displayName: Use Node.js $(nodeVersion)
    inputs:
      versionSpec: $(nodeVersion)

  - task: AzureStaticWebApp@0
    displayName: Deploy Azure Static Web App
    inputs:
      app_location: '/'
      output_location: 'dist/sst-consulting-portal'
      skip_api_build: true
      azure_static_web_apps_api_token: $(azure_static_web_apps_api_token)
      production_branch: 'main'
